<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dev_test_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $form['#validate'][] = '_dev_test_user_login_form_validate';

}

function _dev_test_user_login_form_validate(&$form, FormStateInterface $form_state) {
  Drupal::service('developer_suite.command_bus')->execute($command);
}
